products = [
  {
    '_id': '1',
    'name': 'Colorful Stylish Tiles',
    'image': '/images/Product1.jpg',
    'description':
      'Can be used in any room in your home including kitchen, dining room, bedrooms, bathrooms, foyers and basements. It is also suitable for commercial use in hotels, restaurants, offices, shops, etc.',
    'brand': 'Local',
    'category': 'Tiles',
    'price': 1009.99,
    'countInStock': 0,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Grey Tiles',
    'image': '/images/Product2.jpg',
    'description':
    'Can be used in any room in your home including kitchen, dining room, bedrooms, bathrooms, foyers and basements. It is also suitable for commercial use in hotels, restaurants, offices, shops, etc.',
    'brand': 'Usman Tiles',
    'category': 'Tiles',
    'price': 1599.99,
    'countInStock': 427,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Wood Style Tiles',
    'image': '/images/Product3.jpg',
    'description':
    'Can be used in any room in your home including kitchen, dining room, bedrooms, bathrooms, foyers and basements. It is also suitable for commercial use in hotels, restaurants, offices, shops, etc.',
    'brand': 'Ali Tiles',
    'category': 'Tiles',
    'price': 1929.99,
    'countInStock': 500,
    'rating': 3,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'Design Tiles',
    'image': '/images/Product4.jpg',
    'description':
    'Can be used in any room in your home including kitchen, dining room, bedrooms, bathrooms, foyers and basements. It is also suitable for commercial use in hotels, restaurants, offices, shops, etc.',
    'brand': 'Ali Tiles',
    'category': 'Tiles',
    'price': 1399.99,
    'countInStock': 1100,
    'rating': 5,
    'numReviews': 12,
  },
  {
    '_id': '5',
    'name': 'White Tiles',
    'image': '/images/Product5.jpg',
    'description':
    'Can be used in any room in your home including kitchen, dining room, bedrooms, bathrooms, foyers and basements. It is also suitable for commercial use in hotels, restaurants, offices, shops, etc.',
    'brand': 'Local',
    'category': 'Tiles',
    'price': 1149.99,
    'countInStock': 7000,
    'rating': 3.5,
    'numReviews': 10,
  },
  {
    '_id': '6',
    'name': 'Wooden Door',
    'image': '/images/Product8.jpeg',
    'description':
      'Can be used in any room in your home including kitchen, dining room, bedrooms, bathrooms, foyers and basements. It is also suitable for commercial use in hotels, restaurants, offices, shops, etc.',
    'brand': 'WoodWorkers',
    'category': 'Doors',
    'price': 2229.99,
    'countInStock': 1000,
    'rating': 4,
    'numReviews': 12,
  },
]
